language: node_js
node_js:
- "4"
branches:
  only:
  - manster

cache:
  apt: true
  directories:
    - node_modules

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
- export TZ='Asia/Shanghai'
- npm insall hexo-cli -g
- openssl aes-256-cbc -K $encrypted_0fe06694a206_key -iv $encrypted_0fe06694a206_iv
  -in .travis/id_rsa_qeio.enc -out ~\/.ssh/id_rsa_qeio -d
- chmod 600 ~/.ssh/id_rsa_qeio
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa_qeio
- cp .travis/ssh_config ~/.ssh/config
#设置github账户
- git config --global user.name "jackLucky"
- git config --global user.email 262348314@qq.com

install:
- npm install

script:
- hexo clean && hexo g -d
